// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHcvZRJdYiQquUKVtmMRVT_nfJJQDEve0',
    appId: '1:339250930789:web:62f2db3fc80a4fda11d28c',
    messagingSenderId: '339250930789',
    projectId: 'estoqueappauth',
    authDomain: 'estoqueappauth.firebaseapp.com',
    storageBucket: 'estoqueappauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQKWGOdY_lUr0DLHvq15sziwxbNyzKJ8',
    appId: '1:339250930789:android:b3577b78a76dd41511d28c',
    messagingSenderId: '339250930789',
    projectId: 'estoqueappauth',
    storageBucket: 'estoqueappauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApihnTNd3ZB7fOMHekZ-NavLhYHNK3TYY',
    appId: '1:339250930789:ios:8c29f03ec8d3cea111d28c',
    messagingSenderId: '339250930789',
    projectId: 'estoqueappauth',
    storageBucket: 'estoqueappauth.firebasestorage.app',
    iosBundleId: 'com.example.estoqueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApihnTNd3ZB7fOMHekZ-NavLhYHNK3TYY',
    appId: '1:339250930789:ios:8c29f03ec8d3cea111d28c',
    messagingSenderId: '339250930789',
    projectId: 'estoqueappauth',
    storageBucket: 'estoqueappauth.firebasestorage.app',
    iosBundleId: 'com.example.estoqueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHcvZRJdYiQquUKVtmMRVT_nfJJQDEve0',
    appId: '1:339250930789:web:f321b3d1e4584c7d11d28c',
    messagingSenderId: '339250930789',
    projectId: 'estoqueappauth',
    authDomain: 'estoqueappauth.firebaseapp.com',
    storageBucket: 'estoqueappauth.firebasestorage.app',
  );
}
